version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: full_stack_ecommerce
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: your_database_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./01-starter-files/db-scripts:/docker-entrypoint-initdb.d

  # Spring Boot Backend
  backend:
    build:
      context: ./backend/spring-boot-ecommerce
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/full_stack_ecommerce?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ecommerceapp
      SPRING_DATASOURCE_PASSWORD: your_database_password_here
      STRIPE_KEY_SECRET: sk_test_your_stripe_secret_key_here
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  # Angular Frontend
  frontend:
    build:
      context: ./frontend/angular-ecommerce
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data:
